name = "BEASTTreeUtils"
uuid = "50d08f4b-470a-40f3-9a42-30e5f4b6ae4e"
authors = ["Gabe Hassler <gabriel.w.hassler@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
PhyloNetworks = "33ad39ac-ed31-50eb-9b15-43d0656eaa72"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
